const ACTIONS = {
  ADD_TASK: "ADD_TASK",
  DELETE_TASK: "DELETE_TASK",
  TOGGLE_TASK_STATUS: "TOGGLE_TASK_STATUS",
  DELETE_ALL_TASKS: "DELETE_ALL_TASKS",
  GET_ALL_TASKS: "GET_ALL_TASKS",
  SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER",
  VisibilityFilters: {
    SHOW_ALL: "SHOW_ALL",
    SHOW_COMPLETED: "SHOW_COMPLETED",
    SHOW_ACTIVE: "SHOW_ACTIVE",
  },
};

export default ACTIONS;
